### ISSUE TITLE
add variants of font: bold, italic

### ISSUE THREAD

**Issue by anandkumar89** [mzguntalan/rem-tex#3]
Currently, after installing the plugin, entire document has bold font. It'd be useful to add other font-faces for normal weight, italic.

I'm using remnote app on Mac.

**Comment by mzguntalan** [comment]
Hello @anandkumar89 , thank you. 

If you take a look at the readme/docs there are pictures there to show what remnote should look like after the plugin. There you would see the it does have these varying font weights/styles.

Have you installed the CMU Font? (Computer Modern Font). If you have and the problem persists, could you attach a screenshot of a sample rem?

Thanks

**Comment by anandkumar89** [comment]
Thank you @mzguntalan, not all typefaces were installed on my machine. I've installed it now.

for reference, I'll leave source for CMU font : https://www.fontsquirrel.com/fonts/computer-modern
